# config.yaml

data_loader:
  offline_file: 'data/hk18/offlindata_HK_45.txt'
  online_file: 'data/hk18/onlindata_HK_453.txt'
  kla_dir: 'data/data(kla)/'  # Directory containing all KLA files
  column_separator: '\t'
  decimal_separator: ','
  encoding: 'utf-8'

data_processor:
  online_numeric_columns:
    - 'spH'
    - 'spO2'
    - 'NStirrer'
    - 'sTR'
    - 'sCO2'
    - 'sO2'
    - 'FAirIn'
    - 'sVR'
    - 'FGlucose'

plotter:
  figsize_main: [17, 12]
  figsize_kla: [14, 8]
  style: 'darkgrid'
  plot_dir: '../plots'  # Directory where plots will be saved
  dpi: 300  # Resolution for saved plots

logging:
  level: 'INFO'
  format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    - type: 'stream'
    - type: 'file'
      filename: '../logs/application.log'  # Optional: Log file path
