[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data_handler"
version = "0.1.0"
description = "A project for loading, processing, and visualizing biochemical and fermentation data."
authors = [
    { name = "Bogdan Sprinzl", email = "Bogdan-Sprinzl@hotmail.de" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }

[project.urls]
"Homepage" = "https://github.com/yourusername/data_handler"
"Repository" = "https://github.com/yourusername/data_handler"
"Documentation" = "https://github.com/yourusername/data_handler/wiki"

[project.dependencies]
pandas = ">=1.3.0"
matplotlib = ">=3.4.0"
seaborn = ">=0.11.0"
PyYAML = ">=5.4.0"
pytest = ">=7.0.0"
pytest-mock = ">=3.0.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--cov=src --cov-report=term-missing"
testpaths = ["tests"]

[tool.isort]
profile = "black"

[tool.black]
line-length = 88
target-version = ['py37']

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
skip_covered = true
